"""initial schema

Revision ID: ac2e5ee7272b
Revises:
Create Date: 2026-10-07 12:38:01.093542
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.base
from alembic import op

revision: str = "ac2e5ee7272b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "algorithm_params",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column(
            "value", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("clinically_validated", sa.Boolean(), nullable=False),
        sa.Column("updated_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_algorithm_params")),
    )
    op.create_table(
        "macro_zones",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("label", sa.String(length=30), nullable=False),
        sa.Column("base_hours", sa.Numeric(precision=5, scale=1, asdecimal=False), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_macro_zones")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Enum("PATIENT", "DOCTOR", name="user_role", native_enum=False, length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("accepted_terms_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "doctors",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("license_number", sa.String(length=40), nullable=True),
        sa.Column("specialty", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_doctors_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_doctors")),
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("used_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_reset_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_reset_tokens_token_hash")),
    )
    op.create_index(op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False)
    op.create_table(
        "patients",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("grid_size", sa.SmallInteger(), nullable=False),
        sa.Column("timezone", sa.String(length=40), nullable=False),
        sa.Column("birth_date", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint("grid_size IN (2, 4, 6)", name=op.f("ck_patients_grid_size")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_patients_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_patients")),
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_push_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscriptions")),
        sa.UniqueConstraint("endpoint", name=op.f("uq_push_subscriptions_endpoint")),
    )
    op.create_index(op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "assistant_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", "TOOL", name="message_role", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.String(length=40), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("model", sa.String(length=60), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("blocked_by_guardrail", sa.Boolean(), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.user_id"],
            name=op.f("fk_assistant_messages_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_messages")),
    )
    op.create_index(op.f("ix_assistant_messages_created_at"), "assistant_messages", ["created_at"], unique=False)
    op.create_index(op.f("ix_assistant_messages_patient_id"), "assistant_messages", ["patient_id"], unique=False)
    op.create_table(
        "doctor_patient_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.user_id"],
            name=op.f("fk_doctor_patient_links_doctor_id_doctors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.user_id"],
            name=op.f("fk_doctor_patient_links_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctor_patient_links")),
    )
    op.create_index(op.f("ix_doctor_patient_links_doctor_id"), "doctor_patient_links", ["doctor_id"], unique=False)
    op.create_index(op.f("ix_doctor_patient_links_patient_id"), "doctor_patient_links", ["patient_id"], unique=False)
    op.create_table(
        "dose_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.user_id"], name=op.f("fk_dose_schedules_patient_id_patients"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dose_schedules")),
        sa.UniqueConstraint("patient_id", "time", name="uq_dose_schedules_patient_time"),
    )
    op.create_index(op.f("ix_dose_schedules_patient_id"), "dose_schedules", ["patient_id"], unique=False)
    op.create_table(
        "injections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("macro", sa.String(length=3), nullable=False),
        sa.Column("side", sa.String(length=1), nullable=False),
        sa.Column("row", sa.SmallInteger(), nullable=False),
        sa.Column("col", sa.SmallInteger(), nullable=False),
        sa.Column("grid_size", sa.SmallInteger(), nullable=False),
        sa.Column("microzone_id", sa.String(length=12), nullable=False),
        sa.Column("applied_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("registered_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("REGISTERED", "UNDONE", name="injection_status", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("undone_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "color_at_registration",
            sa.Enum("RED", "YELLOW", "GREEN", name="color", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("warning_accepted", sa.Boolean(), nullable=False),
        sa.Column("previous_last_used", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "origin",
            sa.Enum(
                "MAP", "SUGGESTION", "REMINDER", "ASSISTANT", name="injection_origin", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.CheckConstraint("side IN ('I', 'D')", name=op.f("ck_injections_side")),
        sa.ForeignKeyConstraint(["macro"], ["macro_zones.code"], name=op.f("fk_injections_macro_macro_zones")),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.user_id"], name=op.f("fk_injections_patient_id_patients"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_injections")),
    )
    op.create_index(op.f("ix_injections_microzone_id"), "injections", ["microzone_id"], unique=False)
    op.create_index(op.f("ix_injections_patient_id"), "injections", ["patient_id"], unique=False)
    op.create_index("ix_injections_patient_registered", "injections", ["patient_id", "registered_at"], unique=False)
    op.create_table(
        "link_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("expires_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("used_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.user_id"], name=op.f("fk_link_codes_patient_id_patients"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_link_codes")),
        sa.UniqueConstraint("code", name=op.f("uq_link_codes_code")),
    )
    op.create_index(op.f("ix_link_codes_patient_id"), "link_codes", ["patient_id"], unique=False)
    op.create_table(
        "reminders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_for", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("due_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "SNOOZED",
                "CONFIRMED",
                "SKIPPED",
                name="reminder_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("sent_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("snooze_count", sa.SmallInteger(), nullable=False),
        sa.Column("injection_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["injection_id"], ["injections.id"], name=op.f("fk_reminders_injection_id_injections"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.user_id"], name=op.f("fk_reminders_patient_id_patients"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["dose_schedules.id"],
            name=op.f("fk_reminders_schedule_id_dose_schedules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
        sa.UniqueConstraint("schedule_id", "scheduled_for", name="uq_reminders_schedule_slot"),
    )
    op.create_index(op.f("ix_reminders_due_at"), "reminders", ["due_at"], unique=False)
    op.create_index(op.f("ix_reminders_patient_id"), "reminders", ["patient_id"], unique=False)
    op.create_index(op.f("ix_reminders_scheduled_for"), "reminders", ["scheduled_for"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminders_scheduled_for"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_patient_id"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_due_at"), table_name="reminders")
    op.drop_table("reminders")
    op.drop_index(op.f("ix_link_codes_patient_id"), table_name="link_codes")
    op.drop_table("link_codes")
    op.drop_index("ix_injections_patient_registered", table_name="injections")
    op.drop_index(op.f("ix_injections_patient_id"), table_name="injections")
    op.drop_index(op.f("ix_injections_microzone_id"), table_name="injections")
    op.drop_table("injections")
    op.drop_index(op.f("ix_dose_schedules_patient_id"), table_name="dose_schedules")
    op.drop_table("dose_schedules")
    op.drop_index(op.f("ix_doctor_patient_links_patient_id"), table_name="doctor_patient_links")
    op.drop_index(op.f("ix_doctor_patient_links_doctor_id"), table_name="doctor_patient_links")
    op.drop_table("doctor_patient_links")
    op.drop_index(op.f("ix_assistant_messages_patient_id"), table_name="assistant_messages")
    op.drop_index(op.f("ix_assistant_messages_created_at"), table_name="assistant_messages")
    op.drop_table("assistant_messages")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_table("patients")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_table("doctors")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("macro_zones")
    op.drop_table("algorithm_params")
    # ### end Alembic commands ###
